/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author USUARIO
 */
public class Calculadora extends javax.swing.JFrame {

    private char operador;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resultado = new javax.swing.JTextField();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBinario = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jBCuadrado = new javax.swing.JButton();
        jBNum_negativo1 = new javax.swing.JButton();
        jBPorcentaje1 = new javax.swing.JButton();
        jResta = new javax.swing.JButton();
        jGuardoNum = new javax.swing.JLabel();
        jBIgual = new javax.swing.JButton();
        jBSuma1 = new javax.swing.JButton();
        jBMultiplicación = new javax.swing.JButton();
        jBDivisión = new javax.swing.JButton();
        jBPunto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1080, 768));

        Resultado.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Resultado.setText("0");
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        jB7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jBinario.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBinario.setText("BIN");
        jBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinarioActionPerformed(evt);
            }
        });

        jDelete.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jDelete.setText("DEL");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jB4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB0.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jB3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jBCuadrado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBCuadrado.setText("^2");
        jBCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCuadradoActionPerformed(evt);
            }
        });

        jBNum_negativo1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBNum_negativo1.setText("-/+");
        jBNum_negativo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNum_negativo1ActionPerformed(evt);
            }
        });

        jBPorcentaje1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBPorcentaje1.setText("%");
        jBPorcentaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPorcentaje1ActionPerformed(evt);
            }
        });

        jResta.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jResta.setText("-");
        jResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaActionPerformed(evt);
            }
        });

        jGuardoNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jGuardoNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jGuardoNum.setText("0");
        jGuardoNum.setToolTipText("");
        jGuardoNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jBIgual.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBIgual.setText("=");
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });

        jBSuma1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBSuma1.setText("+");
        jBSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuma1ActionPerformed(evt);
            }
        });

        jBMultiplicación.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBMultiplicación.setText("*");
        jBMultiplicación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicaciónActionPerformed(evt);
            }
        });

        jBDivisión.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBDivisión.setText("/");
        jBDivisión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisiónActionPerformed(evt);
            }
        });

        jBPunto.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBPunto.setText(".");
        jBPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jB9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBSuma1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jResta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBMultiplicación, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBDivisión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jBCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGuardoNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Resultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNum_negativo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBPorcentaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGuardoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Resultado))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSuma1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNum_negativo1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jResta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPorcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMultiplicación, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBDivisión, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jBIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        //Método que captura el click    
        //Resultado.setText("7");

        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("7");
        } else {
            Resultado.setText(antes + "7");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        //Resultado.setText("8");
        String antes = Resultado.getText();
        //Resultado.setText(antes+"8");
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("8");
        } else {
            Resultado.setText(antes + "8");
        }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        //Resultado.setText(antes+"9");
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("9");
        } else {
            Resultado.setText(antes + "9");
        }
        //Resultado.setText("9");
    }//GEN-LAST:event_jB9ActionPerformed

    private void jBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinarioActionPerformed
        // TODO add your handling code here:
        String valorString = Resultado.getText();
        int valor = Integer.parseInt(valorString);
        Resultado.setText(Integer.toBinaryString(valor));
    }//GEN-LAST:event_jBinarioActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        Resultado.setText("");
        jGuardoNum.setText("");
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("4");
        } else {
            Resultado.setText(antes + "4");
        }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("5");
        } else {
            Resultado.setText(antes + "5");
        }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("6");
        } else {
            Resultado.setText(antes + "6");
        }

    }//GEN-LAST:event_jB6ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("1");
        } else {
            Resultado.setText(antes + "1");
        }

    }//GEN-LAST:event_jB1ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("0");
        } else {
            Resultado.setText(antes + "0");
        }

    }//GEN-LAST:event_jB0ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("3");
        } else {
            Resultado.setText(antes + "3");
        }

    }//GEN-LAST:event_jB3ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase("0")) {
            Resultado.setText("2");
        } else {
            Resultado.setText(antes + "2");
        }

    }//GEN-LAST:event_jB2ActionPerformed

    private void jBCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCuadradoActionPerformed
        // TODO add your handling code here:
        String contenido = Resultado.getText();
        Double valor = Double.parseDouble(contenido);
        Double cuadrado = Math.pow(valor, 2);
        Resultado.setText(String.valueOf(cuadrado));

    }//GEN-LAST:event_jBCuadradoActionPerformed

    private void jBNum_negativo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNum_negativo1ActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.charAt(0) == '-') {
            Resultado.setText(antes.substring(1));
        } else {
            Resultado.setText("-" + antes);
        }
    }//GEN-LAST:event_jBNum_negativo1ActionPerformed

    private void jBPorcentaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPorcentaje1ActionPerformed
        // TODO add your handling code here:
        String contenido = Resultado.getText();
        Double valor = Double.parseDouble(contenido);
        Double porcentaje = valor / 100;
        Resultado.setText(String.valueOf(porcentaje));

    }//GEN-LAST:event_jBPorcentaje1ActionPerformed

    private void jRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaActionPerformed
        // TODO add your handling code here:
        //El mas moverá el contenido a la JGuardoNum y dejar a 0 la pantalla
        jGuardoNum.setText(Resultado.getText());
        Resultado.setText("");
        operador = '-';

    }//GEN-LAST:event_jRestaActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed
        // TODO add your handling code here:
        //Se suma lo que hay en memoria más jGuardoNum
        Double memoria = Double.valueOf(jGuardoNum.getText());
        Double valor = Double.valueOf(Resultado.getText());
        Double operacion = 0.0;
        if (operador == '+') {
            operacion = valor + memoria;
        } else if (operador == '-') {
            operacion = memoria - valor;
        } else if (operador == '*') {
            operacion = valor * memoria;
        } else if (operador == '/') {
            operacion = valor / memoria;
        }

        Resultado.setText(String.valueOf(operacion));
        jGuardoNum.setText("0");


    }//GEN-LAST:event_jBIgualActionPerformed

    private void jBSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuma1ActionPerformed
        // TODO add your handling code here:
        jGuardoNum.setText(Resultado.getText());
        Resultado.setText("");
        operador = '+';

        Double memoria = Double.valueOf(jGuardoNum.getText());
        Double valor = Double.valueOf(Resultado.getText());
        Double operacion = 0.0;
        operacion = valor + memoria;
        Resultado.setText(String.valueOf(operacion));
        jGuardoNum.setText("0");

    }//GEN-LAST:event_jBSuma1ActionPerformed

    private void jBMultiplicaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicaciónActionPerformed
        // TODO add your handling code here:
        jGuardoNum.setText(Resultado.getText());
        Resultado.setText("");
        operador = '*';

    }//GEN-LAST:event_jBMultiplicaciónActionPerformed

    private void jBDivisiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisiónActionPerformed
        // TODO add your handling code here:
        jGuardoNum.setText(Resultado.getText());
        Resultado.setText("");
        operador = '/';
    }//GEN-LAST:event_jBDivisiónActionPerformed

    private void jBPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPuntoActionPerformed
        // TODO add your handling code here:
        String antes = Resultado.getText();
        if (antes.equalsIgnoreCase(".")) {
            Resultado.setText(".");
        } else {
            Resultado.setText(antes + ".");
        }
    }//GEN-LAST:event_jBPuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Resultado;
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBCuadrado;
    private javax.swing.JButton jBDivisión;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMultiplicación;
    private javax.swing.JButton jBNum_negativo1;
    private javax.swing.JButton jBPorcentaje1;
    private javax.swing.JButton jBPunto;
    private javax.swing.JButton jBSuma1;
    private javax.swing.JButton jBinario;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jGuardoNum;
    private javax.swing.JButton jResta;
    // End of variables declaration//GEN-END:variables
}
